spring:
  datasource:
    url: jdbc:h2:file:E:/FIDO/JobPortalFido/Job-Portal/data;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      # ddl-auto: create-drop  # Ensures tables are created
      ddl-auto: update  # Ensures tables are created
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    session:
      creation-policy: IF_REQUIRED  # Create a session if needed

server:
  servlet:
    session:
      timeout: 30m  # ✅ Session tồn tại 30 phút
      cookie:
        secure: true
        http-only: true
      tracking-modes: cookie

